version: '3.7'

services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile
    image: tex-template:latest
    container_name: template_uqac
    environment:
      CLEAN: ${CLEAN}
    networks:
      - latex-net
    volumes:
      - ./src:/tex/src

networks:
  latex-net:
    name: latex-net
