version: 2
jobs:
  build:
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run:
          name: Copy Files
          command: cp -R src/* /tex/src
      - run:
          name: Change Directory 
          command: 'cd /tex/src'
      - run:
          name: Build LaTeX 
          command: 'make build'
      - store_artifacts:
          path: /tmp/artifacts