version: 2
jobs:
  build:
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run:
          name: Copy Files
          command: src/* .
      - run:
          name: Build LaTeX 
          command: 'make build'
      - run:
          name: Copy Artifact
          commad: 'cp main.pdf /tmp/artifacts/'
      - store_artifacts:
          path: /tmp/artifacts